version: "3"
services:
  app:
    build: ./
    volumes:
      - ./laravel-nuxt:/var/www/html
    ports:
      - 8000:8000
    expose:
      - 9000
    environment:
      - HOST=0.0.0.0
  nginx:
    image: nginx:alpine
    ports:
      - 80:80
    links:
      - app
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./laravel-nuxt:/var/www/html
